### ISSUE TITLE
Specifications

### ISSUE THREAD

**Issue by iliawnek** [iliawnek/SystematicReview#3]
- accounts
  - [x] create account
  - [x] edit account
- reviews
  - [x] create review
  - [x] edit review
  - [x] delete review
- queries
  - input
    - [x] advanced input (text field)
    - [x] simple input (visual interface)
    - [ ] view number of papers returned by query while entering
  - actions
    - [x] save query
    - [x] edit query
    - [x] delete query
    - [x] queries after the first should add/subtract from abstract pool
- pools
  - [x] view list of papers in abstract pool
  - [x] view list of papers in document pool
  - [x] judge papers in abstract/document pool
  - [x] view title/authors/abstract of paper in abstract pool
  - [x] give link of paper in document pool
  - [x] view list of papers in final pool

**Comment by nallar** [comment]
> "Essentially only one query is submitted, though it might be composed of a number of parts. The researcher will perform a number of query refinements to reduce the set of results down to a manageable size. And then save the query, and thus save the documents so that they can then be judged."

from leifos on moodle discussions.
